# pyproject.toml

[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mqtt-gateway"
version = "1.0.0"
dependencies = [
    "paho-mqtt",
    "dbus-python",
    "PyGObject",
]
